// ══════════════════════════════════════════════════════════════════════
// AUTOMATIONS DATA — the fixed-rule jobs that are NOT AI agents
// ══════════════════════════════════════════════════════════════════════
// Created 27 Aug 2026 by the estate audit.
//
// WHY THIS FILE EXISTS. Austin Chen's Agent Assignment Matrix splits work in
// two: judgement work goes to an agent, deterministic if/then goes to what he
// calls "simple automation". An agent doing an if/then is over-engineering, so
// these deliberately do NOT get rows in the AI Agents register — putting them
// through the AGENTIC stages would be dressing a conditional up as a colleague.
// They are listed here, on the same page, because Kevin's rule is that nothing
// is hidden: the more we build, the easier it is to forget what an older job
// does, and you cannot safely retire what you cannot describe.
//
// THE TEST FOR THIS LIST: no AI model is called anywhere in the job. Every
// entry below was checked by reading its source. If a job starts calling a
// model, it stops being an automation and needs a register row instead.
//
// KEEPING IT HONEST: `tests/automations-coverage.test.js` fails whenever
// scripts/job-schedule.json holds a job that is missing from MAC_JOBS below,
// so a new scheduled job cannot quietly go unlisted. The Cloudflare and
// Airtable groups have no machine-readable source available to the browser,
// so those are maintained by hand — add to them in the same commit that adds
// the worker or automation.

var AUTOMATIONS = {

    // ── Scheduled jobs on Kevin's Mac (launchd) ───────────────────────
    // `key` must match the key in scripts/job-schedule.json.
    macJobs: [
        { key: 'session-keepalive', name: 'Session Keep-alive', when: '6:40am daily', status: 'on',
          what: 'Visits every website the robot stays logged into, so those logins do not quietly expire from disuse. If one has logged out, it raises a single sign-in item for your 8am message instead of letting a job stall on it later. Government sites are left alone: those need your code every time.' },
        { key: 'mcp-inventory', name: 'Tools & Connections List', when: '6:10am daily', status: 'on',
          what: 'Rebuilds the list of every outside system the AI is plugged into, on the AI Agents page. Reads the real settings rather than a list someone remembered to update, and refuses to write a shorter list if it cannot read one of its sources properly. When something has genuinely changed it tests its own work and, if it passes, ships the update itself, so the page cannot drift behind your actual setup. If its tests fail it leaves the change waiting for you instead.' },
        { key: 'drift-scan', name: 'Drift Scan', when: '6:20am daily', status: 'on',
          what: 'Reads the code looking for references to things that no longer exist: a field that was renamed, a file that was deleted, a page that was retired. It reports them so a broken link is found before it breaks something.' },
        { key: 'estate-status', name: 'Estate Status Board', when: 'every 10 minutes', status: 'on',
          what: 'Writes one line per scheduled job to the Estate Status table: when it last ran, whether it worked, why not in plain words, and when it is next due, plus the list of tasks that are not moving, and the everything-built list the Track record tab reads (built from the real files by scripts/built_inventory.py). The Estate status tab on the AI Agents page reads it. If this job stops, that tab says so.' },
        { key: 'tenant-leads', name: 'Tenant-finding chain', when: '8:10am daily', status: 'on',
          what: 'Finds rooms that need a tenant (a void, a notice, or a room move adopted on the Growth Plan) and keeps single people aged 35 or over on Universal Credit coming in. It drafts one email card for your queue to the council, charity and support contacts near the room, one to our tenants about the £50 referral bonus (only the tenants Roy has said to ask: it sends him the list by name first and reads his yes or no), and a monthly check-in to people on the list. It gives Roy the adverts to post and a list of qualified people to call for viewings. It screens every sign-up from the form. When Roy says someone wants a room, it gives him a move-in checklist (right to rent, proof of Universal Credit, a reference, the signing, then the works and the move-in date) and drafts one email card asking that person for their documents. It checks each house with an open room against the compliance book, so nobody new moves in before the house is legal, and names who is fixing each one, and puts a £50 bonus on the Friday Payment Run when a referred tenant pays their first rent. It writes the Tenant-finding chain line on the Estate status board and one line in your 09:00 brief, which turn red when a step that should have happened did not.' },
        { key: 'estate-drift', name: 'CEO and Board Currency Check', when: '6:25am daily', status: 'on',
          what: 'Checks that the AI CEO, the eleven department heads, the five workers, the CEO skills, the morning huddle instructions, the brain files the CEO reads first and the 9am brief are all describing how the business runs TODAY. It looks for wording a decision has retired (for example routing work to Mica after that stopped, or the old spending thresholds) and for any decision newer than the CEO\'s own "as at" page. Red means a prompt is out of date and gets fixed the same day. Built the day Kevin said he had stopped using his CEO because he felt outdated.' },
        { key: 'content-engine', name: 'Content Engine folder watch', agent: true, when: '10:00pm daily', status: 'on',
          what: 'Looks in the Runpreneur raw video folder on Drive for clips it has not seen, creates one "Episode N Full Episode" record per new shooting day (New Upload) and copies the oldest waiting clip to this Mac, then turns one pulled clip into the three Runpreneur videos (full 16:9 with captions, LFMD and Summary 9:16 with the banner), files them in the edited Drive folder, writes the links and transcript onto the episode record, then writes the platform copy for that episode in Kevin\'s voice using the Content Machine\'s own prompts and checks it against the writing rules, and when an episode has its video, thumbnail and copy it puts ONE approval card in Kevin\'s queue (counted by the 8am digest) and copies his verdict back onto the episode. For episodes Kevin has APPROVED it schedules the full episode to YouTube and, the night after YouTube publishes, the Summary and Learnings clips to Facebook, LinkedIn, TikTok (and Instagram, Threads once connected) through GoHighLevel, publishes the blog article on runpreneur.org.uk, then writes the published links back, and redraws the How far I\'ve run map page on the website from Strava (route marker, countries, facts). The full episode carries the branded intro after Kevin\'s sign-off, the podcast upload plan is written for the browser lane, and the website\'s "How far I\'ve run" numbers and the Strava run name are updated from Strava and Stripe. Nothing is scheduled without his approval on the card.' },
        { key: 'content-engine-publish', name: 'Content Engine daytime publisher', when: 'hourly 7:15am to 8:15pm', status: 'on',
          what: 'Every hour in the day it reads Kevin\'s verdicts on the episode cards, puts the next approved episode (in day order) on YouTube, and once YouTube gives the link it schedules that episode\'s clips with their copy to the socials, the blog article and the podcast for later the same day. No rendering; the night job does that.' },
        { key: 'content-report-live', name: 'Publishing page live check', when: 'every 10 minutes', status: 'on',
          what: 'Keeps the Publishing page (Marketing) no more than about ten minutes behind, day and night, even while a render is running. It asks GoHighLevel about any post whose slot has passed, counts a YouTube upload as live once its slot passes, and reads your verdict on any episode card still open, then rewrites the page\'s report. It only reads: it never posts, uploads or changes what the publisher has recorded. Facebook profile shares and Spotify links still confirm hourly, because they need the robot browser.' },
        { key: 'data-invariants', name: 'Data Invariants Check', when: '6:40am daily', status: 'on',
          what: 'Checks the real Airtable data still obeys the rules it is supposed to. Each check has a control, so if the check itself breaks it fails loudly instead of quietly passing. This is the check that would have caught the 8,667 blanked transactions.' },
        { key: 'drive-auth', name: 'Drive Login Check', when: '6:50am daily', status: 'on',
          what: 'Checks the Google Drive login has not expired. The brain lives in Drive, so an expired login silently stops several other jobs. This catches it in the morning rather than a week later.' },
        { key: 'project-status-sync', name: 'Project Status Sync', when: '6:45am daily', status: 'on',
          what: 'Writes each project\'s health, worked out from its tasks and cash target, back to the Projects table in Airtable, so the Airtable grid agrees with the dashboard (which works it out for itself).' },
        { key: 'masterplan-sync', name: 'Master Plan Sync', when: '7:00am daily', status: 'on',
          what: 'Keeps MASTER-PLAN.md and Airtable in step: ticks a plan line when its Airtable task completes, and turns an open, dated plan line with no task into one (never for a person who takes no work). Commits the plan back from its own private copy, never the shared checkout.' },
        { key: 'signature-watch', name: 'Signed Document Watch', when: '9:20am, 12:20pm, 3:20pm, 6:20pm daily', status: 'on',
          what: 'Watches for documents you sent out for signature coming back signed. When one is done it downloads the signed copy and files it, so it can be put in front of you for the second approval before it is posted or emailed. It checks Adobe itself rather than waiting for an email, because an email can be filtered or archived and the signed copy has to come from Adobe anyway. If it cannot see your Adobe account it says so loudly instead of reporting that nothing has been signed.' },
        { key: 'knowledge-os-sort', name: 'Knowledge Sorter', when: '8:50am daily', status: 'on',
          what: 'Files new brain documents into the right folder using the naming rules. It moves files, it does not read or judge them.' },
        { key: 'publish-brain', name: 'Brain Publisher', when: '11:20pm daily', status: 'on',
          what: 'Publishes the brain to the private feed the web app reads, so the Today tab shows current information.' },
        { key: 'apple-notes-bridge', name: 'Apple Notes Bridge', when: '10:40pm daily', status: 'on',
          what: 'Pulls anything you wrote in the Apple Notes "Brain" folder, and the Reminders lists "Captures" and "Call Log", into the brain inbox, so notes made on your phone are not stranded there.' },
        { key: 'audiobook-morning-report', name: 'Audiobook Morning Report', when: '8:00am daily', status: 'on',
          what: 'Reports what the Audiobook Processor got through overnight: books transcribed, books turned into brain documents, anything that failed. It only reports. The Audiobook Processor agent does the thinking.' },
        { key: 'job-digest', name: 'Job Digest', when: '11:00am daily', status: 'on',
          what: 'One summary of every scheduled job and whether it ran, was skipped, or failed. This is how a job that quietly stopped gets noticed. Since 1 Sep 2026 it writes to its log only — no Slack (Kevin retired system alerts).' },
        { key: 'daily-ops-guard', name: 'Daily Sweep Guard', when: '9:30am daily', status: 'on',
          what: 'Proves the 7am Daily Sweep actually ran. A routine cannot be trusted to report its own absence, so something outside it has to check. Since 1 Sep 2026 an alarm goes to its log and a Mac notification only — no Slack.' },
        { key: 'retry-deferred', name: 'Retry Deferred Jobs', when: 'every hour', status: 'on',
          what: 'Re-runs a scheduled job that was turned away earlier because the Mac was not ready, once the thing that blocked it has cleared. Your Mac only tries each job once, at its set time, so a job that could not run because Google Drive was asleep used to just lose the day. That is how the brain went four days without being fed in August 2026. It only re-runs jobs that have been signed up for it, and it says out loud when a job lost the day anyway.' },
        { key: 'mac-guard', name: 'Mac Guard', when: 'every hour', status: 'on',
          what: 'Kills leftover preview servers that outlived the session that started them. They hold ports forever otherwise. It only touches servers over 4 hours old with nothing connected.' },
        { key: 'uc-notifier-watchdog', name: 'UC Notifier Watchdog', when: '9:00am daily', status: 'off',
          what: 'Proved the Universal Credit list was actually sent, after it failed silently twice. RETIRED 1 Sep 2026 with the whole UC check process (Kevin\u2019s ruling); the script is now a stub.' },
        { key: 'uk-gigs', name: 'UK Gigs Watch', when: '7:30am daily, checks weekly', status: 'on',
          what: 'Reads every artist with 5 or more songs in Kevin’s Apple Music library, looks up their UK dates on Ticketmaster once a week, and emails Kevin the new ones with date, venue, city and booking link. Artists are matched by Ticketmaster’s own id, so a tribute act never passes as the real band, and artists it cannot find are listed at the foot of every email. For favourite bands that no longer tour, the best UK tribute acts get their own clearly labelled section. A month with nothing new still gets one email, so a broken job never looks like a quiet month.' },
        { key: 'magic-battery', name: 'Magic Device Batteries', when: 'hourly, reminder at 9:30pm', status: 'on',
          what: 'Reads the battery level of the Magic Keyboard, Trackpad and Mouse on the Mac mini every hour. When one is at 20% or below, it puts a "charge it tonight" reminder in Kevin’s Apple Reminders at 9:30pm, and ticks it off once the device reads above 20% again. A device not seen for two days gets its own reminder, so a flat or switched-off device never reads as fine.' },
        { key: 'home-battery', name: 'Smart Home Batteries', when: 'hourly, reminder at 9:30pm', status: 'on',
          what: 'Reads every Aqara device in the house from Aqara\u2019s developer service, and every battery Home Assistant on the Mac mini knows about (the tado radiator valves and thermostats, Yale, Bosch, Sonos), every hour: the battery level of each sensor, switch and blind, and whether each device (cameras and doorbell included) is online. At 9:30pm it puts one reminder in Kevin\u2019s Apple Reminders for each battery at 20% or below and each device offline for two hours or more, and ticks it off once a fresh reading shows the problem is gone. Built after the Office camera dropped off unnoticed on 28 Sep 2026. A device that vanishes from Aqara\u2019s list gets one reminder too. If it cannot read Aqara for 12 hours (signed out, no internet, a half-empty list) it says so with its own reminder, so silence never reads as all clear.' },
        { key: 'utilita-balance', name: 'Duckworth Electric Watch', when: 'hourly, message once each morning', status: 'on',
          what: 'Reads the pay-as-you-go electric balance on both Duckworth serviced flats and sends Kevin and Roy one Slack message a day with the figures and the days left. It runs hourly because Utilita signs you out after an hour unless something looks in, so most runs only keep the login alive. If a login does lapse it says SIGN-IN NEEDED rather than reporting a blank, and it refuses to report a balance at all if the meter behind a login has changed.' },
        { key: 'handback-poll', agent: true, name: 'Hand-back Poll', when: 'every 30 minutes', status: 'on',
          what: 'Runs the hand-back check for the Work Dispatcher agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'roy-assistant', agent: true, name: "Roy's assistant", when: 'every 10 minutes, 7am to 9pm', status: 'on',
          what: "Picks up what Roy forwards from info@ to info@, has the Inbox Response agent work it straight away, and emails Roy what happened. Every email to a tenant, contractor or agent still waits for Kevin's yes." },
        { key: 'daily-ops', agent: true, name: 'Systems Check', when: '7:00am daily', status: 'on',
          what: 'Runs the Systems Check agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'inbound-triage', agent: true, name: 'Inbox Triage', when: '9am, 1pm, 5pm', status: 'on',
          what: 'Runs the Inbox Triage agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'task-manager', agent: true, name: 'Task Board Manager', when: '9:20am, 1:20pm, 5:20pm', status: 'on',
          what: 'Runs the Task Board Manager agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'ceo-agent', agent: true, name: 'CEO Brief', when: '6:45am daily', status: 'on',
          what: 'Runs the CEO Brief agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'prospecting', agent: true, name: 'Lead Finder', when: '9:15am daily', status: 'off',
          what: 'Runs the Lead Finder agent, which has its own register row above. PARKED 27 Sep 2026: Kevin parked Operations Director to January 2027, so no prospecting runs until then.' },
        { key: 'prod-sweep-weekly', agent: true, name: 'Site Tester', when: 'Sundays 11:00am', status: 'on',
          what: 'Runs the Site Tester agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'uc-check', agent: true, name: 'UC Verification', when: '8:00am daily', status: 'off',
          what: 'Runs the UC Verification agent, which has its own register row above. RETIRED 1 Sep 2026: Kevin stopped the whole UC check process \u2014 missed payments are handled as arrears instead.' },
        { key: 'audiobook-backfill', agent: true, name: 'Audiobook Processor', when: 'midnight daily', status: 'on',
          what: 'Runs the Audiobook Processor agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'feed-brain', agent: true, name: 'Brain Feeder', when: '10:45pm daily', status: 'on',
          what: 'Runs the Brain Feeder agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'compound-brain', agent: true, name: 'Brain Compounder', when: '11:00pm daily', status: 'on',
          what: 'Runs the Brain Compounder agent, which has its own register row above. Listed here so every scheduled job is accounted for.' },
        { key: 'payment-run-daily', name: 'Payment Run daily check', when: '6:30am daily', status: 'on',
          what: 'Keeps the Payment Run list true between Fridays. It puts the payment cards you approved on the list on the Friday before they are due, marks a bill Paid once the bank shows a payment that names the payee, and lists any money that left the business account without ever being on the list. No AI, so it costs nothing to run.' },
        { key: 'payment-run', agent: true, name: 'Payment Run', when: 'Fridays 9:00pm', status: 'on',
          what: 'Finds every payment request across Kevin\u2019s two mailboxes, reads the PDF invoices, checks nothing has already been paid, and leaves one list in Accounts > Payment Run. It prepares only \u2014 it never pays, sends or agrees anything.' },
    ],

    // Scheduled outside job-schedule.json, so the coverage test does not see it.
    otherMacJobs: [
        { key: 'photo-filer', name: 'Photo Filer', when: '3:15am daily', status: 'on',
          what: 'Files new Apple Photos into albums by rule, add-only: it never deletes or moves a photo out of an album. Unsure items go to a "To review" album.' },
        { key: 'phone-context', name: 'Phone Assistant Context', when: '3:15am daily', status: 'on',
          what: 'Copies memory and project notes into a Drive folder the phone assistant reads, so it knows what this Mac knows.' },
        { key: 'homeassistant-vm', name: 'Home Assistant VM', when: 'at login', status: 'on',
          what: 'Starts the Home Assistant virtual machine in the background when the Mac logs in.' },
        { key: 'stay-awake', name: 'Stay Awake', when: 'always', status: 'on',
          what: 'Keeps the Mac from sleeping, so scheduled jobs are not suspended mid-run.' },
        { key: 'ebay-arb', name: 'eBay Price Sweep', when: '7:30am daily', status: 'on',
          what: 'Sweeps eBay auction listings (golf and other products) for items selling for less than they are worth, and logs what it finds to its own local page. It is pure arithmetic on prices. Nothing here reads a listing or decides anything, which is why it is an automation and not an agent, despite being called an engine.' },
    ],

    // ── Cloudflare Workers ────────────────────────────────────────────
    workers: [
        { name: 'claude-proxy', when: 'on request', status: 'on',
          what: 'Passes AI requests from the web app through to Anthropic, so the API key stays on the server and never reaches the browser.' },
        { name: 'anthropic-proxy', when: 'on request', status: 'on',
          what: 'The repo\'s anthropic-proxy.js source deploys AS claude-proxy (cloudflare-worker/wrangler.toml, name = "claude-proxy"). Whether a separate worker still runs under the old name was not checked from here.' },
        { name: 'slack-notify', when: 'on request', status: 'on',
          what: 'Sends Slack messages on behalf of the web app. It is a postbox: it writes nothing itself.' },
        { name: 'drive-upload', when: 'on request', status: 'on',
          what: 'Uploads files to Google Drive, and is also the transport that sends approved emails as you, reads and labels mail for Inbox Triage, and creates calendar entries. It only sends what a script hands it, and only from an address you have connected.' },
        { name: 'apple-inbound', when: 'on request', status: 'on',
          what: 'Takes voice notes and forwarded texts into the system, and relays Slack messages to you or Roy. Its voice-note route USES AN AI MODEL to turn a note into a task (source in workers/apple-inbound/worker.js), so that route is not a fixed rule.' },
        { name: 'sms-email-bridge', when: 'every minute', status: 'on',
          what: 'Turns incoming text messages into emails so they land in the inbox with everything else, and sends a reply to one of those emails back to the sender as a text.' },
        { name: 'prospect-reply-watch', when: 'every 2 minutes', status: 'on',
          what: 'Watches for replies from prospects, marks them Replied, sends you a Slack message with a preview of the reply text, and opens a task to draft an answer. No AI in it. Still runs while Operations Director prospecting is parked.' },
        { name: 'agent-runner', agent: true, when: '8:00am daily and on request', status: 'on',
          what: 'Runs the Systemisation page\'s autonomous workflows through an AI model and logs each run to Agent Activity. It calls a model, so it is shown here but not counted as a fixed-rule automation.' },
        { name: 'skill-runner', when: 'on request', status: 'on',
          what: 'Passes a skill run through to the AI model when something asks it to. It is a relay, like claude-proxy: the thinking happens in the model, not here.' },
        { name: 'ghl-sms-proxy', when: 'on request', status: 'on',
          what: 'Passes text messages to and from GoHighLevel.' },
        { name: 'content-machine-proxy', when: 'on request', status: 'on',
          what: 'Connects the separate Content Machine project to this one.' },
        { name: 'od-billing-bridge', when: 'on request', status: 'on',
          what: 'Handles billing messages for Operations Director client payments.' },
        { name: 'onboarding-form', when: 'on request', status: 'on',
          what: 'Serves the form a new client fills in when they sign up, and files their answers.' },
        { name: 'property-manager', when: 'on request', status: 'on',
          what: 'Feeds Roy\'s Property Manager page from Airtable behind its own passcode, strips personal money out before anything reaches the page, and lets Roy update his tasks.' },
        { name: 'ceo-brief-tenants', when: 'off', status: 'off',
          what: 'The client-product version of the CEO Brief, writing to Supabase. Its schedule was removed on 8 Sep 2026 when the Supabase migration was parked.' },
        { name: 'loom-transcript', when: 'on request', status: 'on',
          what: 'Fetches the transcript of a Loom video when something needs it.' },
        { name: 'fpl-relay', when: 'on request', status: 'on',
          what: 'Belongs to Fantasy Football Meta, a separate product bet. Nothing in Operations Director depends on it.' },
        { name: 'money-confidence-daily', agent: true, when: '9:00am weekdays', status: 'on',
          what: 'Sends the CEO Brief agent\'s 9am Slack message. The agent has its own register row above; this worker is the delivery half. Listed here so every deployed worker on a schedule is accounted for.' },
        { name: 'contractor-bot', agent: true, when: 'every minute', status: 'on',
          what: 'Since 1 Sep 2026 the every-minute timer sends you ONE approvals digest at 8am (count plus a link to the dashboard queue; on a day with nothing waiting it still sends the content report line) and still posts Mica\u2019s lane cards to her DM and reads her emoji back. Your per-task cards, the contractor chat and the CEO DM chat are retired \u2014 the webhook now only turns replies under task DMs into task comments. Do not remove this cron: it carries the 8am digest and Mica\u2019s cards.' },
    ],

    // ── Airtable automations ──────────────────────────────────────────
    // 50 exist. 34 are deployed (live), 16 are undeployed (built but switched
    // off). Exactly ONE calls an AI model — "Auto Generate SOP AI Fields" —
    // and that one has a register row instead. Descriptions below come from
    // each automation's TRIGGER and action nodes, which were read directly.
    // Where a script body was not read, the entry says what the script is
    // called rather than guessing what it does.
    airtable: [
        { name: 'Cashflow Monthly Report, BMS and TMS Generator', when: 'daily', status: 'on', group: 'Money',
          what: 'Builds the monthly money records: the cashflow report, and the business and tenancy monthly summaries. Five scripts in a row.' },
        { name: 'Cashflow Forecast Automation', when: 'daily', status: 'on', group: 'Money',
          what: 'Recalculates money in and money out for the cash flow forecast.' },
        { name: 'Rolling 12 P&L', when: '1st of the month', status: 'on', group: 'Money',
          what: 'Creates the profit and loss record for the new month so the rolling 12-month view stays complete.' },
        { name: 'Split Transactions', when: 'when a transaction is split', status: 'on', group: 'Money',
          what: 'When you split one bank transaction across several categories, this creates the separate parts.' },
        { name: 'Tenancy Payments', when: 'on a matching rent payment', status: 'on', group: 'Money',
          what: 'Marks rent as received against the right tenancy when a matching payment lands.' },
        { name: 'Link Business Record to Transaction', when: 'on transaction change', status: 'on', group: 'Money',
          what: 'Attaches the right business to a transaction so reports split correctly.' },
        { name: 'Transaction to BMS Table Linking', when: 'on transaction change', status: 'on', group: 'Money',
          what: 'Links a transaction to the business monthly summary it belongs to.' },
        { name: 'Transaction to TMS Table Linking', when: 'on transaction change', status: 'on', group: 'Money',
          what: 'Links a transaction to the tenancy monthly summary it belongs to.' },
        { name: 'Transaction to SAS Table Linking', when: 'on transaction change', status: 'on', group: 'Money',
          what: 'Links a transaction to the statement summary it belongs to.' },
        { name: 'Link BMS Table to Personal Cashflow Statement', when: '1st of the month', status: 'on', group: 'Money',
          what: 'Joins the business monthly summaries to your personal cashflow statement, and starts the month for the maintenance KPI.' },
        { name: 'Finance Workflow Add record to Rental Unit Maintenance KPI', when: 'on a maintenance cost', status: 'on', group: 'Property',
          what: 'Records a maintenance cost against the right rental unit so the maintenance KPI is accurate.' },
        { name: 'New Tenancy to Rental Unit Metrics', when: 'on new tenancy', status: 'on', group: 'Property',
          what: 'Adds a new tenancy into the rental unit metrics so occupancy and rent figures update.' },
        { name: 'Tenant and Tenancy linked, mark Unit Occupied or Void', when: 'on tenancy change', status: 'on', group: 'Property',
          what: 'Flips a rental unit to Occupied when a tenant is linked, and back to Void when they are not.' },
        { name: 'When task is assigned, send Slack alert', when: 'on assignee change', status: 'on', group: 'Tasks',
          what: 'Tells someone in Slack that a task has been given to them.' },
        { name: 'When Task is Completed, notify collaborators', when: 'on completion', status: 'on', group: 'Tasks',
          what: 'Tells everyone attached to a task that it is done.' },
        { name: 'When Task is Completed by assignee, alert everyone else', when: 'on completion', status: 'on', group: 'Tasks',
          what: 'Same as above but skips the person who completed it, so nobody is told their own news.' },
        { name: 'Track Previous Assignee', when: 'on assignee change', status: 'on', group: 'Tasks',
          what: 'Remembers who had a task before it was reassigned.' },
        { name: 'Task created under Project Tasks Dashboard, set Priority to Project', when: 'on task create', status: 'on', group: 'Tasks',
          what: 'Marks a task as project work so it does not compete with today’s list.' },
        { name: 'New project task gets business and department', when: 'on task create', status: 'on', group: 'Tasks',
          what: 'Fills in the business and department on a new project task from the project it belongs to.' },
        { name: 'Task linked to a Project, add collaborators', when: 'on project link', status: 'on', group: 'Tasks',
          what: 'Adds the project’s people to a task when it joins that project.' },
        { name: 'Someday task assigned, clear the Someday flag', when: 'on assignee change', status: 'on', group: 'Tasks',
          what: 'If you assign a someday task to someone, it stops being someday.' },
        { name: 'Someday ticked, clear the date fields', when: 'on Someday tick', status: 'on', group: 'Tasks',
          what: 'Clears the dates off a task you have pushed to someday, so it stops showing as due.' },
        { name: 'New task, set the original due date after 15 mins', when: 'every 15 minutes', status: 'on', group: 'Tasks',
          what: 'Stamps the first due date a task was given, 15 minutes after it is created, so later changes can be measured against it.' },
        { name: 'Update Due Date, Strategy Project Planning', when: 'on date change', status: 'on', group: 'Tasks',
          what: 'Keeps strategy project dates in step when one moves.' },
        { name: 'Time from Time Estimate sync', when: 'on estimate change', status: 'on', group: 'Tasks',
          what: 'Copies the time estimate into the time field so workload adds up.' },
        { name: 'Inbound Comms: remove approval when task is assigned', when: 'on assignee change', status: 'on', group: 'Tasks',
          what: 'Takes an inbound item out of the approval queue once a person has picked it up.' },
        { name: 'SOP Task Creation', when: 'on SOP needing a video', status: 'on', group: 'Processes',
          what: 'Creates the task to record a Loom when an SOP needs one.' },
        { name: 'SOP For Approval', when: 'on SOP status change', status: 'on', group: 'Processes',
          what: 'Posts to Slack when an SOP is ready for you to approve.' },
        { name: 'Needs Updating SOP Process', when: 'on SOP flagged', status: 'on', group: 'Processes',
          what: 'Marks an SOP as needing an update and raises the task to do it.' },
        { name: 'Untick SOP Required When Loom Is Added', when: 'on video added', status: 'on', group: 'Processes',
          what: 'Clears the "needs a video" flag once the video exists.' },
        { name: 'Create New SOP then link it', when: 'on task change', status: 'on', group: 'Processes',
          what: 'Creates a new SOP record from a task and links the two together.' },
        { name: 'Objective Plan Form Add Task', when: 'on form submit', status: 'on', group: 'Strategy',
          what: 'Turns an objective plan form submission into a task.' },
        { name: 'OD Payment, Onboarding Customer Journey', when: 'on payment webhook', status: 'on', group: 'Clients',
          what: 'Starts a new client’s onboarding when their payment comes through.' },
    ],

    // Built but switched off in Airtable. Listed so a switched-off automation
    // is a visible decision rather than a thing nobody remembers exists.
    airtableOff: [
        'Task Completion Date', 'Task Created - Link to Team Member',
        'Task Configuration Upon Creation', 'Recurring Tasks',
        'When task has Linked Project, set Priority to Project',
        'When Due Date is updated, adjust the Status',
        'SOP to Create Recurring Task (Initial)',
        'When assignee is changed, add them as collaborator',
        'Auto Rescheduling of Tasks with Calendar Time Block',
        'Advance Due Date after Payment', 'Sync Payment Cost Status',
        'CFV Logger automation', 'Team Capacity Sync Tasks to Team Members',
        'Auto Suggest Categories V2', 'Daily Needle Mover Slack Report',
        'Cumulative Balance for Account Statement',
    ],
};
